[package]
name = "image-processing-service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = {version="1.0.99", features=["derive"]}

[dependencies.uuid]
version = "1.16.0"
# Lets you generate random UUIDs
features = [
    "v4",
]
